### ISSUE TITLE
Issues on Firefox

### ISSUE THREAD

**Issue by lazyguyy** [slyphiX/bingo#1]
Hey dud,  
I bet you're thinking that you're an awesome programmer, cause you took my template and added "real" programming languages, such as html and css. But guess what, prick, it doesn't work on firefox correctly (the print preview for 6 bingos looks worse than the toilet at my local mcdonalds). Could you please do something right for once?? I'm sitting here, like, oh cool, he built something on my bingo generator, turns out it's a bunch of crap using my expensive computation time. thanks man, never gonna use this shitty generator again!!!111!
fix pls.

**Comment by lazyguyy** [comment]
no progress made? looks like this script kiddie doesn't know what to do anymore LOL

**Comment by slyphix** [comment]
Fixed. Thanks for reporting.

**Comment by lazyguyy** [comment]
No problem at all. I honestly love how respectful the github community deals with each other. Like I build this awesome bingo generator, and then a fellow computer science student sees it and thinks to himself 'I bet browser integration would be a really cool addition'. That in itself is awesome. But then, you know, I notice the repository myself and while im fumbling around with it (totally in awe by the way, your code is so clean!), I find a tiny bug. Dutyfully I write a detailed and easily-understandable bug report to make this whole project even better than it already is, and suddenly – blink and you would have missed it, you know, a month really is not that much when you consider the complexity of this project – everything is fixed. I am honestly very very proud of you and the github community (and actually, humanity in general), things like these make life worthwile and never fail to put a smile on my face.
Thank you for taking your time to fix this miniscule bug (I mean, it only made the whole project unusable on firefox, so whatever) and being the awesome person that you are. Keep being you, and one day a renowned company such as Oracle might hire you for your impressive software development techniques.
